Entity/Construct.php
<?php

/*
 * Copyright 2013 Radoslaw Kamil Ejsmont <radoslaw@ejsmont.net>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Bluemesa\Bundle\ConstructBundle\Entity;

use Bluemesa\Bundle\AclBundle\Entity\SecureEntity;
use Bluemesa\Bundle\CoreBundle\Entity\MutableIdEntityInterface;
use Bluemesa\Bundle\CoreBundle\Entity\NamedTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * Construct class
 *
 * @ORM\Entity(repositoryClass="Bluemesa\Bundle\ConstructBundle\Repository\ConstructRepository")
 * @Serializer\ExclusionPolicy("all")
 * @Vich\Uploadable
 * @UniqueEntity("id")
 *
 * @author Radoslaw Kamil Ejsmont <radoslaw@ejsmont.net>
 */
class Construct extends SecureEntity implements MutableIdEntityInterface
{ 
    use NamedTrait;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     * @Serializer\Expose
     * @Assert\NotBlank(message = "Type must be specified")
     *
     * @var string
     */
    protected $type;
    
    /**
     * @ORM\Column(type="float", nullable=true)
     * @Serializer\Expose
     *
     * @var float
     */
    protected $size;

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     * @Serializer\Expose
     *
     * @var array
     */
    protected $resistances;
    
    /**
     * @ORM\Column(type="text", nullable=true)
     * @Serializer\Expose
     * 
     * @var string
     */
    protected $notes;

    /**
     * @ORM\ManyToMany(targetEntity="ConstructTag", cascade={"persist", "remove"})
     * @ORM\JoinTable(name="entity_tags",
     *     joinColumns={@ORM\JoinColumn(name="entity_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn(name="tag_id", referencedColumnName="id")}
     * )
     * @Serializer\Expose
     *
     * @var Collection
     */
    protected $tags;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Serializer\Expose
     *
     * @var string
     */
    protected $vendor;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Serializer\Expose
     * @Assert\Url()
     *
     * @var string
     */
    protected $infoURL;

    /**
     * @ORM\OneToMany(targetEntity="ConstructTube", mappedBy="construct", cascade={"persist"}, fetch="EXTRA_LAZY")
     *
     * @var Collection
     */
    protected $tubes;

    /**
     * @ORM\OneToOne(targetEntity="CloningMethod", mappedBy="construct",
     *     cascade={"persist", "remove"}, orphanRemoval=true)
     *
     * @var CloningMethod
     */
    protected $method;

    /**
     * @Vich\UploadableField(mapping="sequence_file", fileNameProperty="sequenceName")
     *
     * @var File
     */
    protected $sequenceFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     * @var string
     */
    protected $sequenceName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTime
     */
    protected $updatedAt;

    /**
     * @var array
     */
    public static $types = array(
        'Plasmid' => 'plasmid',
        'Fosmid' => 'fosmid',
        'BAC' => 'BAC',
        'Cosmid' => 'cosmid',
        'Linear DNA' => 'linear',
    );

    /**
     * @var array
     */
    public static $antibiotics = array(
        'Ampicillin' => 'Amp',
        'Blasticidin' => 'Bla',
        'Bleocin' => 'Ble',
        'Chroramphenicol'  => 'Cm',
        'Coumermycin' => 'Com',
        'D-cycloserine' => 'DCS',
        'Erythromycin' => 'Ery',
        'Geneticin' => 'Gen',
        'Gentamycin' => 'Gta',
        'Hygromycin' => 'Hgr',
        'Kanamycin' => 'Kan',
        'Kasugamycin' => 'Kas',
        'Nalidixic acid' => 'Nal',
        'Neomycin' => 'Neo',
        'Penicillin' => 'Pen',
        'Puromycin' => 'Pur',
        'Rifampicin' => 'Rif',
        'Spectinomycin' => 'Spe',
        'Streptomycin' => 'Str',
        'Tetracycline' => 'Tet',
        'Triclosan' => 'Tri',
        'Trimethoprim' => 'Tmp',
        'Zeocin' => 'Zeo',
    );


    /**
     * Construct Antibody
     * 
     */
    public function __construct()
    {
        $this->tubes = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->type = 'plasmid';
    }

    /**
     * {@inheritdoc}
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * Get type
     * 
     * @return string
     */
    public function getType() {
        return $this->type;
    }

    /**
     * Set type
     * 
     * @param string $type
     */
    public function setType($type) {
        $this->type = $type;
    }

    /**
     * Get size
     * 
     * @return float
     */
    public function getSize()
    {
        $method = $this->getMethod();
        if ($method instanceof SizedMethodInterface) {
            $size = $method->getSize();
        } else {
            $size = null;
        }

        return ($size !== null) ? $method->getSize() : $this->size;
    }

    /**
     * Set size
     * 
     * @param float $size
     */
    public function setSize($size) {
        $this->size = $size;
    }

    /**
     * Is construct size computed from cloning method
     *
     * @return bool
     */
    public function isSizeComputed()
    {
        $method = $this->getMethod();
        if ($method instanceof SizedMethodInterface) {
            $size = $method->getSize();
        } else {
            $size = null;
        }

        return ($size !== null);
    }

    /**
     * @return array
     */
    public function getResistances()
    {
        return $this->resistances;
    }

    /**
     * @return string
     */
    public function getResistancesText()
    {
        $antibiotics = array_flip(static::$antibiotics);
        $string = "";

        foreach ($this->resistances as $resistance) {
            if (array_key_exists($resistance, $antibiotics)) {
                if (! empty($string)) {
                    $string .= ", ";
                }
                $string .= $antibiotics[$resistance] .  " (" . $resistance . ")";
            }
        }

        return $string;
    }

    /**
     * @param array $resistances
     */
    public function setResistances($resistances)
    {
        $this->resistances = $resistances;
    }

    /**
     * Get notes
     *
     * @return string
     */
    public function getNotes()
    {
        return $this->notes;
    }
    
    /**
     * Set notes
     *
     * @param string $notes
     */
    public function setNotes($notes)
    {
        $this->notes = $notes;
    }

    /**
     * Get tags
     *
     * @return Collection
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Add tag
     *
     * @param ConstructTag $tag
     */
    public function addTag(ConstructTag $tag)
    {
        $tags = $this->getTags();
        if (null !== $tag) {
            if (! $tags->contains($tag)) {
                $tags->add($tag);
            }
        }
    }

    /**
     * Remove tag
     *
     * @param ConstructTag $tag
     */
    public function removeTag(ConstructTag $tag)
    {
        $this->getTags()->removeElement($tag);
    }

    /**
     * Get vendor
     *
     * @return string
     */
    public function getVendor()
    {
        return $this->vendor;
    }

    /**
     * Set vendor
     *
     * @param string
     */
    public function setVendor($vendor)
    {
        $this->vendor = $vendor;
    }

    /**
     * Get info URL
     *
     * @return string
     */
    public function getInfoURL()
    {
        return $this->infoURL;
    }

    /**
     * Set info URL
     *
     * @param string  $infoURL
     */
    public function setInfoURL($infoURL)
    {
        $this->infoURL = $infoURL;
    }
    
    /**
     * Get tubes
     *
     * @return ArrayCollection
     */
    public function getTubes()
    {
        return $this->tubes;
    }
    
    /**
     * Add tube
     *
     * @param ConstructTube $tube
     */
    public function addTube(ConstructTube $tube)
    {
        $tubes = $this->getTubes();
        if (null !== $tube) {
            if (! $tubes->contains($tube)) {
                $tubes->add($tube);
            }
            if ($tube->getConstruct() !== $this) {
                $tube->setConstruct($this);
            }
        }
    }

    /**
     * Remove tube
     *
     * @param ConstructTube $tube
     */
    public function removeTube(ConstructTube $tube)
    {
        $this->getTubes()->removeElement($tube);
    }

    /**
     * @return CloningMethod
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * @param CloningMethod $method
     */
    public function setMethod($method)
    {
        $this->method = $method;
        if (null !== $method) {
            if ($method->getConstruct() !== $this) {
                $method->setConstruct($this);
            }
        }
    }

    /**
     * @return File
     */
    public function getSequenceFile()
    {
        return $this->sequenceFile;
    }

    /**
     * @param File $sequenceFile
     */
    public function setSequenceFile(File $sequenceFile = null)
    {

Controller/ConstructController.php
<?php

/*
 * This file is part of the ConstructBundle.
 *
 * Copyright (c) 2016 BlueMesa LabDB Contributors <labdb@bluemesa.eu>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Bluemesa\Bundle\ConstructBundle\Controller;

use Bluemesa\Bundle\CoreBundle\Controller\Annotations\Paginate;
use Bluemesa\Bundle\CrudBundle\Controller\Annotations as CRUD;
use Bluemesa\Bundle\CrudBundle\Controller\CrudControllerTrait;
use FOS\RestBundle\Controller\Annotations as REST;
use FOS\RestBundle\Request\ParamFetcher;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


/**
 * Class ConstructController
 *
 * @author Radoslaw Kamil Ejsmont <radoslaw@ejsmont.net>
 *
 * @REST\Prefix("/constructs")
 * @REST\NamePrefix("bluemesa_construct_")
 * @CRUD\Controller()
 */
class ConstructController extends Controller
{
    use CrudControllerTrait;

    /**
     * @CRUD\Action("index")
     * @CRUD\Filter("Bluemesa\Bundle\ConstructBundle\Filter\ConstructFilter", redirectRoute="bluemesa_construct_index_type_sort")
     * @REST\View()
     * @REST\Get("", defaults={"_format" = "html"}))
     * @REST\Get("/{type}", name="_type",
     *     requirements={"type" = "plasmid|genomic|synthetic|all"},
     *     defaults={"_format" = "html"}))
     * @REST\Get("/sort/{sort}/{order}", name="_sort",
     *     requirements={"sort" = "id|name|type"},
     *     defaults={"_format" = "html", "type" = "all", "sort" = "id", "order" = "asc"})
     * @REST\Get("/{type}/sort/{sort}/{order}", name="_type_sort",
     *     requirements={"type" = "plasmid|genomic|synthetic|all", "sort" = "id|name|type"},
     *     defaults={"_format" = "html", "type" = "all", "order" = "asc"})
     * @Paginate(25)
     *
     * @param  Request     $request
     * @return View
     */
    public function indexAction(Request $request)
    {
        return $this->getCrudHandler()->handle($request);
    }

    /**
     * @CRUD\Action("show")
     * @REST\View()
     * @REST\Get("/{id}", requirements={"id"="\d+"}, defaults={"_format" = "html"})
     *
     * @param  Request     $request
     * @return View
     */
    public function showAction(Request $request)
    {
        return $this->getCrudHandler()->handle($request);
    }

    /**
     * @CRUD\Action("new")
     * @REST\View()
     * @REST\Route("/new", methods={"GET", "POST"}, defaults={"_format" = "html"})
     * @REST\Post("", name="_rest", defaults={"_format" = "html"})
     *
     * @param  Request     $request
     * @return View
     */
    public function newAction(Request $request)
    {
        return $this->getCrudHandler()->handle($request);
    }

    /**
     * @CRUD\Action("edit")
     * @REST\View()
     * @REST\Route("/{id}/edit", methods={"GET", "PUT"}, requirements={"id"="\d+"}, defaults={"_format" = "html"})
     * @REST\Put("/{id}", name="_rest", requirements={"id"="\d+"}, defaults={"_format" = "html"})
     *
     * @param  Request     $request
     * @return View
     */
    public function editAction(Request $request)
    {
        return $this->getCrudHandler()->handle($request);
    }

    /**
     * @CRUD\Action("delete")
     * @REST\View()
     * @REST\Route("/{id}/delete", methods={"DELETE"}, requirements={"id"="\d+"}, defaults={"_format" = "html"})
     * @REST\Delete("/{id}", name="_rest", requirements={"id"="\d+"}, defaults={"_format" = "html"})
     *
     * @param  Request     $request
     * @return View
     */
    public function deleteAction(Request $request)
    {
        return $this->getCrudHandler()->handle($request);
    }

    /**
     * @REST\Post("/_ajax/method/form", defaults={"_format" = "html"}, requirements={"_format" = "html"})
     * @REST\RequestParam(name="entity")
     * @REST\RequestParam(name="form")
     *
     * @param  Request      $request
     * @param  ParamFetcher $paramFetcher
     * @return Response
     */
    public function ajaxFormAction(Request $request, ParamFetcher $paramFetcher)
    {
        $entityClass = $paramFetcher->get('entity');
        $formClass = $paramFetcher->get('form');

        $data = array('method' => new $entityClass());
        $builder = $this->container->get('form.factory')
            ->createNamedBuilder('construct', FormType::class, $data)
            ->add('method', $formClass, array(
                'horizontal_label_offset_class' => null,
                'horizontal_input_wrapper_class' => 'construct_method_placeholder',
                'label_render'      => false,
                'widget_form_group' => false
            ))
            ;

        return new Response($this->renderView('BluemesaConstructBundle:Construct:ajaxform.html.twig',
            array('form' => $builder->getForm()->createView())));
    }
}

Resources/views/Construct/ajaxForm.html.twig
{{ form_rest(form) }}

Resources/views/Construct/edit.html.twig
{% extends "BluemesaConstructBundle:Construct:layout.html.twig" %}
{% use "BluemesaSiteTemplateBundle:Form:form.html.twig" %}
{% import "BluemesaSiteTemplateBundle:Macros:form.html.twig" as f %}

{% block headline %}Constructs{% endblock headline %}
{% block modal_header %}Edit construct{% endblock modal_header %}

{% block modal_body %}
  {{ form_errors(form) }}
  {{ form_rest(form) }}
  {% if form.method is not defined %}
  <div class="construct_method_placeholder"></div>
  {% endif %}
{% endblock modal_body %}

{% block modal_footer %}
  <button type="submit" class="btn btn-primary">Save</button>
  {% set value = form.vars.value %}
  {% if value.id is not null %}
    {% if is_granted('ROLE_ADMIN') or is_granted('DELETE',value) %}
    <a href="{{ path('bluemesa_construct_show', { 'id': value.id }) }}" class="btn btn-danger">Delete</a>
    {% endif %}
    <a href="{{ path('bluemesa_construct_show', { 'id': value.id }) }}" class="btn btn-default">Cancel</a>
  {% else %}
    <a href="{{ path('bluemesa_construct_index') }}" class="btn btn-default">Cancel</a>
  {% endif %}
{% endblock modal_footer %}

{% block foot_script_additional %}
<script>
  $(document).ready(function () {
    $("#construct_cloningMethod").on("change", function (e) {
      if(this.value) {
        data = $.parseJSON(this.value);
        $.post('{{ path('bluemesa_construct_ajax_form') }}', data, function(data, status) {
          $('.construct_method_placeholder').replaceWith(data);
          $('.select2').not('.select2-container').not('.select2-offscreen').select2({
            width: 'resolve',
            minimumResultsForSearch: -1
          });
        });
      } else {
        $('.construct_method_placeholder').replaceWith('<div class="construct_method_placeholder"></div>');
      }
    });
  });
</script>
{% endblock %}

Resources/views/Construct/gateway.html.twig
{% import "BluemesaSiteTemplateBundle:Macros:show.html.twig" as s %}

{{ s.row("Cloning method", "Gateway") }}
<div class="form-group">
  <a class="control-label col-sm-3 collapse-toggle" data-toggle="collapse" href="#vector">
    <strong>Entry vector</strong>
  </a>
</div>
<div id="vector" class="collapse">
  {{ s.row("Name", method.vector) }}
  {{ s.row("Size", method.vectorSize ~ ((method.vectorSize > 0) ? "kb" : "")) }}
</div>
<div class="form-group">
  <a class="control-label col-sm-3 collapse-toggle" data-toggle="collapse" href="#insert"><strong>Insert</strong></a>
</div>
<div id="insert" class="collapse">
  {{ s.row("Name", method.insert) }}
  {{ s.row("Size", method.insertSize ~ ((method.insertSize > 0) ? "kb" : "")) }}
  {{ s.row("Orientation", method.insertOrientationText) }}
</div>
<div class="form-group">
  <a class="control-label col-sm-3 collapse-toggle" data-toggle="collapse" href="#destinationVector">
    <strong>Destination vector</strong>
  </a>
</div>
<div id="destinationVector" class="collapse">
    {{ s.row("Name", method.destinationVector) }}
    {{ s.row("Size", method.destinationVectorSize ~ ((method.destinationVectorSize > 0) ? "kb" : "")) }}
</div>

Resources/views/Construct/getConstruct.html.twig
{% extends "BluemesaConstructBundle:Construct:layout.html.twig" %}
{% use "BluemesaSiteTemplateBundle:Show:modal.html.twig" %}
{% import "BluemesaSiteTemplateBundle:Macros:show.html.twig" as s %}
{% import 'BluemesaSiteTemplateBundle:Macros:status.html.twig' as status %}

{% block modal_header %}
  #{{ construct.id }} - {{ construct }}
{% endblock modal_header %}

{% block modal_body %}
  {{ s.row("Type", construct.type) }}
  {{ s.row("Size", construct.size) }}
{% endblock modal_body %}

{% block modal_footer %}
{% endblock modal_footer %}

Resources/views/Construct/getConstructs.html.twig
{% extends "BluemesaConstructBundle:Construct:layout.html.twig" %}
{% use "BluemesaSiteTemplateBundle:List:table.html.twig" %}
{% import "BluemesaSiteTemplateBundle:Macros:list.html.twig" as l %}
{% import 'BluemesaSiteTemplateBundle:Macros:status.html.twig' as status %}

{% block headline %}Constructs{% endblock headline %}

{% block list_header %}
  {% include 'BluemesaConstructBundle:Construct:head.html.twig' %}
{% endblock list_header %}

{% block list_item %}
  {% include 'BluemesaConstructBundle:Construct:row.html.twig' with {'entity': entity} %}
{% endblock list_item %}

{% block list_buttons %}
{% endblock list_buttons %}

Resources/views/Construct/head.html.twig
<th>ID</th>
<th>Name</th>
<th>Type</th>
<th>Size</th>
<th>Resistances</th>

Resources/views/Construct/index.html.twig
{% extends "BluemesaConstructBundle:Construct:layout.html.twig" %}
{% use "BluemesaSiteTemplateBundle:List:table.html.twig" %}
{% import "BluemesaSiteTemplateBundle:Macros:list.html.twig" as l %}
{% import 'BluemesaSiteTemplateBundle:Macros:status.html.twig' as status %}

{% block headline %}Constructs{% endblock headline %}

{% block list_header %}
  {% include 'BluemesaConstructBundle:Construct:head.html.twig' %}
{% endblock list_header %}

{% block list_item %}
  {% include 'BluemesaConstructBundle:Construct:row.html.twig' with {'entity': entity} %}
{% endblock list_item %}

{% block list_buttons %}
{% endblock list_buttons %}

Resources/views/Construct/layout.html.twig
{% extends "BluemesaConstructBundle::layout.html.twig" %}

{% block headline %}Constructs{% endblock headline %}

{% block content_sidebar %}
  {% block sidebar_display %}
    <form class="panel panel-default panel-condensed" action="{{ path('bluemesa_construct_index') }}" method="GET">
      <div class="panel-heading">
        <h3 class="panel-title"><a data-toggle="collapse" href="#dislpay">List options</a></h3>
      </div>
      <ul id="dislpay" class="list-group collapse mobile-collapsed in">
        {% block sidebar_display_filters %}
          <li class="list-group-item">
            <h5>Filters</h5>
            <ul>
              <li>
                <label>
                  <input class="toggle-children" type="radio" name="type" id="type_all" value="all"
                          {{ (filter is not defined or filter.type == 'all') ? 'checked' }} >
                  All constructs
                </label>
              </li>
              <li>
                <label>
                  <input class="toggle-children" type="radio" name="type" id="type_plasmids" value="plasmid"
                          {{ (filter is defined and filter.type == 'plasmid') ? 'checked' }} >
                  Plasmids
                </label>
              </li>
              <li>
                <label>
                  <input class="toggle-children" type="radio" name="type" id="type_genomic" value="genomic"
                          {{ (filter is defined and filter.type == 'genomic') ? 'checked' }} >
                  Genomic constructs
                </label>
              </li>
              <li>
                <label>
                  <input class="toggle-children" type="radio" name="type" id="type_synthetic" value="linear"
                          {{ (filter is defined and filter.type == 'linear') ? 'checked' }} >
                  Linear DNA
                </label>
              </li>
            </ul>
          </li>
        {% endblock sidebar_display_filters %}
        {% block sidebar_display_sort %}
          <li class="list-group-item">
            <h5>Sort by</h5>
            <ul>
              <li>
                <label>
                  <input type="radio" name="sort" id="sort_id" value="id"
                          {{ (filter is not defined or filter.sort == 'id') ? 'checked' }} >
                  Construct ID
                </label>
              </li>
              <li>
                <label>
                  <input type="radio" name="sort" id="sort_name" value="name"
                          {{ (filter is defined and filter.sort == 'name') ? 'checked' }} >
                  Construct name
                </label>
              </li>
              <li>
                <label>
                  <input type="radio" name="sort" id="sort_type" value="type"
                          {{ (filter is defined and filter.sort == 'type') ? 'checked' }} >
                  Construct type
                </label>
              </li>
              <li>
                <label>
                  <input type="checkbox" name="order" id="order" value="desc"
                          {{ (filter is defined and filter.order == 'desc') ? 'checked' }} >
                  Descending
                </label>
              </li>
            </ul>
          </li>
        {% endblock sidebar_display_sort %}
        <li class="panel-footer">
          <input type="hidden" name="resolver" value="on">
          <button type="submit" class="btn btn-primary btn-sm btn-block">
            List constructs
          </button>
        </li>
      </ul>
    </form>
  {% endblock sidebar_display %}
  {% block sidebar_actions %}
    <div class="panel panel-default panel-condensed">
      <div class="panel-heading">
        <h3 class="panel-title"><a data-toggle="collapse" href="#actions">Actions</a></h3>
      </div>
      <ul id="actions" class="list-group collapse mobile-collapsed in">
        <a class="list-group-item" href="{{ path('bluemesa_construct_new') }}">New construct</a>
        <a class="list-group-item" href="{{ path('bluemesa_construct_search_search') }}">Search</a>
      </ul>
    </div>
  {% endblock sidebar_actions %}
  {{ parent() }}
{% endblock content_sidebar %}

Resources/views/Construct/list.html.twig
{% extends "BluemesaConstructBundle:Construct:layout.html.twig" %}
{% use "BluemesaSiteTemplateBundle:List:table.html.twig" %}
{% import "BluemesaSiteTemplateBundle:Macros:list.html.twig" as l %}
{% import 'BluemesaSiteTemplateBundle:Macros:status.html.twig' as status %}

{% block headline %}Constructs{% endblock headline %}

{% block list_header %}
  {% include 'BluemesaConstructBundle:Construct:head.html.twig' %}
{% endblock list_header %}

{% block list_item %}
  {% include 'BluemesaConstructBundle:Construct:row.html.twig' with {'entity': entity} %}
{% endblock list_item %}

{% block list_buttons %}
{% endblock list_buttons %}

Resources/views/Construct/show.html.twig
{% extends "BluemesaConstructBundle:Construct:layout.html.twig" %}
{% use "BluemesaSiteTemplateBundle:Show:modal.html.twig" %}
{% import "BluemesaSiteTemplateBundle:Macros:show.html.twig" as s %}
{% import 'BluemesaSiteTemplateBundle:Macros:status.html.twig' as status %}

{% block modal_header %}
  #{{ entity.id }} - {{ entity }}
{% endblock modal_header %}

{% block modal_body %}
  {{ s.row("Type", entity.type) }}
  {{ s.row("Resistances", entity.resistancesText) }}
  {{ s.row("Size", entity.size ~ ((entity.size > 0) ? "kb" : "")) }}
  <div class="form-group">
    <label class="control-label col-sm-3">Sequence file</label>
    <div class="col-sm-9">
        <span class="input-text">
          {% if entity.sequenceFile is not empty %}
            <a href="{{ vich_uploader_asset(entity, 'sequenceFile') }}" target="_blank">{{ entity.sequenceFile.filename }}</a>
          {% endif %}
        </span>
    </div>
  </div>
  <div class="form-group">
    <a class="control-label col-sm-3 collapse-toggle" data-toggle="collapse" href="#details"><strong>Details</strong></a>
  </div>
  <div id="details" class="collapse">
    {{ s.row("Notes", entity.notes) }}
  </div>
  <div class="form-group">
    <a class="control-label col-sm-3 collapse-toggle" data-toggle="collapse" href="#vendor"><strong>Vendor information</strong></a>
  </div>
  <div id="vendor" class="collapse">
    {{ s.row("Vendor", entity.vendor) }}
    <div class="form-group">
      <label class="control-label col-sm-3">Info URL</label>
      <div class="col-sm-9">
        <span class="input-text">
          {% if entity.infoURL is not empty %}
            <a href="{{ entity.infoURL }}" target="_blank">{{ entity.infoURL }}</a>
          {% endif %}
        </span>
      </div>
    </div>
  </div>
  {% if entity.method is not empty %}
    {% include "BluemesaConstructBundle:Construct:" ~ entity.method.name ~ ".html.twig" with {'method': entity.method} %}
  {%  endif %}
{% endblock modal_body %}

{% block modal_footer %}
  {% if is_granted('ROLE_ADMIN') or is_granted('EDIT', entity) %}
    <a href="{{ path('bluemesa_construct_edit', { 'id': entity.id }) }}" class="btn btn-primary">Edit</a>
  {% endif %}
  <a href="{{ path('bluemesa_construct_index') }}" class="btn btn-default">List</a>
{% endblock modal_footer %}